
name: vinhci

on:
  push:
    branches: [ "civinh" ]

  workflow_dispatch:

jobs:
  Vinh_build:
    runs-on: ubuntu-latest

    steps:
      - name: Vinh Remote exec ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY }}" >  ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa vinh@34.143.236.100 sh -c  "
            set -x 
            mkdir -p ~/civinh
            
            echo 'git clone code neu chua co'
            cd ~/civinh 
            
            if [ ! -d "~/civinh/todb17_danhsachlop/.git" ]; then
              echo "Chưa có repo, tiến hành clone..."
              git clone git@github.com:zzelda2025/todb17_danhsachlop.git
            else
              echo "Repo đã tồn tại rồi!"
            fi

            echo 'git pull'
            cd ~/civinh/todb17_danhsachlop
            git checkout civinh; git pull
            
            echo 'compose up'  
            cd ~/civinh/todb17_danhsachlop/app
            NAME=TEL4VN ./composeup.sh


            "
