
name: CI

on:
  push:
    branches: [ "civinh" ]

  workflow_dispatch:

jobs:
  Vinh_build:
    runs-on: ubuntu-latest

    steps:
      - name: Vinh Remote exec ssh
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa vinh@34.143.236.100 sh -c 'pwd;ls -a'
          
