# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "civinh" ]

  workflow_dispatch:

jobs:
  Vinh_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Vinh  Run a one-line script
        run: echo  Hello Vinh, world!

      - name: VInh Run a multi-line script
        run: |
          echo Vinh 1 Add other actions to build,
          echo Vinh 2 test, and deploy your project.
      - run: echo whitout name
  vinh_job2:
    runs-on: ubuntu-latest   
    steps:
      - run: echo vinh job2
